#!/usr/bin/env python

import dbus
from geekogotchi_ui import GeekogotchiUI

class GeekogotchiClient:
  ui = None
  bus = None
  def __init__(self):
    self.ui = GeekogotchiUI(self)
    self.ui.connect()
  def connect(self, *args, **kargs):
    '''Connect to Geekogotchi server'''
    if kargs.get('mainloop'):
        self.bus = dbus.SystemBus(mainloop = kargs['mainloop'])
        self.mainloop = True
    else:
        self.bus = dbus.SystemBus()
        self.mainloop = False
    self.server = dbus.Interface(self.bus.get_object('org.shr.Geekogotchi','/org/shr/Geekogotchi/Server'), dbus_interface='org.shr.Geekogotchi.Server')
    self.pets = dbus.Interface(self.bus.get_object('org.shr.Geekogotchi','/org/shr/Geekogotchi/Pets'), dbus_interface='org.shr.Geekogotchi.Pets')
  def disconnect(self):
    '''Disonnect from Geekogotchi server'''
    return None
  def start(self):
    '''Start UI'''
    self.ui.start()
  def stop(self):
    '''Exit from UI mainloop'''
    self.ui.exit()
  def getCharacter(self):
    '''Return character info'''
    # TODO
    return {'Name':'Alik', 'Born':1234567, 'Age': 2, 'Health':100, 'Hungry':0}
  def destroy(self):
    '''Shutting down client'''
    self.ui.destroy()
    self.ui = None

client = GeekogotchiClient()
client.start()
client.destroy()
